include:
    #- project: i40/administration
    #  file: gitlab-ci-maven.yml
    #  ref: main
    - file: gitlab-ci-test.yml

variables:
  MVN_FORBID_SNAPSHOT_DEPENDENCIES_DISABLED : "true"
  MAVEN_DEPLOY_FROM_UNPROTECTED_DISABLED: "true"
  MAVEN_DEPLOY_ENABLED: "true"

docker-publish-aas-server:
  extends: .docker-publish-module
  variables:
    MODULE_NAME: server

docker-publish-knowledgegraph-service:
  extends: .docker-publish-module
  variables:
    MODULE_NAME: knowledgegraph

