<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aas" nsURI="http://www.dfki.de/cos/basys/model/aas" nsPrefix="aas">
  <eClassifiers xsi:type="ecore:EClass" name="AssetAdministrationShell" eSuperTypes="#//HasDataSpecification #//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="derivedFrom" eType="#//AssetAdministrationShell"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="security" lowerBound="1"
        eType="#//Security" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asset" lowerBound="1" eType="#//Asset"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submodel" upperBound="-1"
        eType="#//Submodel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="view" upperBound="-1" eType="#//View"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasDataSpecification" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="administration" eType="#//AdministrativeInformation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identification" eType="#//Identifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asset" eSuperTypes="#//HasDataSpecification #//Identifiable #//HasKind">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assetIdentificationModel"
        eType="#//Submodel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View" eSuperTypes="#//HasDataSpecification #//HasSemantics #//Referable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedElement" upperBound="-1"
        eType="#//Referable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasKind" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//Kind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasSemantics" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticId" eType="#//Reference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Referable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idShort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Referable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Submodel" eSuperTypes="#//HasDataSpecification #//HasKind #//HasSemantics #//Identifiable #//Qualifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" eType="#//Qualifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submodelElement" upperBound="-1"
        eType="#//SubmodelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Qualifiable" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Qualifier" eSuperTypes="#//Constraint #//HasSemantics">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifierType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifierValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifierValueId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubmodelElement" abstract="true" eSuperTypes="#//HasDataSpecification #//HasKind #//HasSemantics #//Qualifiable #//Referable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" eType="#//Qualifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="submodelelement" eType="#//SubmodelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//DataElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="File" eSuperTypes="#//DataElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mimeType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Blob" eSuperTypes="#//DataElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mimeType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceElement" eSuperTypes="#//DataElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Reference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubmodelElementCollection" eSuperTypes="#//SubmodelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowDuplicates" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//SubmodelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="submodelElement" eType="#//SubmodelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="first" lowerBound="1" eType="#//Referable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="second" lowerBound="1"
        eType="#//Referable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationVariable" eSuperTypes="#//SubmodelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//SubmodelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//SubmodelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="in" upperBound="-1" eType="#//OperationVariable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="out" upperBound="-1" eType="#//OperationVariable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true" eSuperTypes="#//SubmodelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Security"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reference"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Kind">
    <eLiterals name="Type"/>
    <eLiterals name="Instance" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idType" eType="#//IdentifierType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IdentifierType">
    <eLiterals name="IRDI"/>
    <eLiterals name="URI" value="1"/>
    <eLiterals name="Custom" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdministrativeInformation" eSuperTypes="#//HasDataSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
