<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="assetAdministration" nsURI="http://www.example.org/assetAdministration"
    nsPrefix="assetAdministration">
  <eClassifiers xsi:type="ecore:EClass" name="AssetAdministrationShell" eSuperTypes="#//HasDataSpecification #//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="security" eType="#//Security"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivedFrom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasDataSpecification" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Security" instanceTypeName="newDataType1"/>
  <eClassifiers xsi:type="ecore:EClass" name="Asset" eSuperTypes="#//HasDataSpecification #//Identifiable #//HasKind">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assetIdentificationModel"
        eType="#//Submodel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assetadministrationshell"
        upperBound="-1" eType="#//AssetAdministrationShell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AssetAdministrationShell" instanceTypeName="newDataType2"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Submodel" instanceTypeName="newDataType3"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Referable" instanceTypeName="newDataType6"/>
  <eClassifiers xsi:type="ecore:EClass" name="View" eSuperTypes="#//HasDataSpecification #//HasSemantics #//Referable.1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containedElement" eType="#//Referable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assetadministrationshell"
        upperBound="-1" eType="#//AssetAdministrationShell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasKind" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="HasSemantics" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Referable" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Submodel" eSuperTypes="#//HasDataSpecification #//HasKind #//HasSemantics #//Identifiable #//Qualifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assetadministrationshell"
        eType="#//AssetAdministrationShell"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" eType="#//Qualifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Qualifiable" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Qualifier" eSuperTypes="#//Constraint #//HasSemantics">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quilifierType" eType="#//QualifierType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifierValue" eType="#//PropertyValueType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifierValueId" eType="#//Reference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="QualifierType" instanceTypeName="newDataType5"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PropertyValueType" instanceTypeName="newDataType6"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Reference" instanceTypeName="newDataType7"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubmodelElement" abstract="true" eSuperTypes="#//HasDataSpecification #//HasKind #//HasSemantics #//Qualifiable #//Referable.1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="submodel" eType="#//Submodel.1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" eType="#//Qualifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="submodelelement" eType="#//SubmodelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//PropertyValueType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataelement" eType="#//DataElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="File">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mimeType" eType="#//MimeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//PathType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataelement" eType="#//DataElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="MimeType" instanceTypeName="newDataType8"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PathType" instanceTypeName="newDataType9"/>
  <eClassifiers xsi:type="ecore:EClass" name="Blob">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mimeType" eType="#//MimeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//BlobType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataelement" eType="#//DataElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BlobType" instanceTypeName="newDataType10"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Reference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataelement" eType="#//DataElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubmodelElementCollection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowDuplicates" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//SubmodelElement.1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submodelelement" eType="#//SubmodelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="SubmodelElement" instanceTypeName="newDataType11"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="first" eType="#//Referable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="second" eType="#//Referable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submodelelement" eType="#//SubmodelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//SubmodelElement.1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submodelelement" eType="#//SubmodelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="in" eType="#//OperationVariable.1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="out" eType="#//OperationVariable.1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationvariable" eType="#//OperationVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submodelelement" eType="#//SubmodelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="submodelelement" eType="#//SubmodelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="OperationVariable" instanceTypeName="newDataType12"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Type" instanceTypeName="newDataType13"/>
</ecore:EPackage>
