logging:
  level:
    org.springframework.boot.autoconfigure: INFO
server:
  port: 8088
basys:
  aas-registry:
    type: dotaas
    service:
      connectionString: http://aasregistry.dockerhost
  aas-server:
    backend: InMemory
    source: C:/Work/basys/docker/aas/data/aas-server/mrklab.aasx
#    mqtt:
#      server: http://dockerhost:1883
    context:
      context-path:
      doc-base:
      hostname: localhost
      port: 8088
